### ISSUE TITLE
Group 2 Phase 2 - PlayDevCardView should not show ResourceCardChooser

### ISSUE THREAD

**Issue by adrfoong** [cs340tabyu/CatanBugTracker#101]
![devcardpicker](https://cloud.githubusercontent.com/assets/9939603/10798348/d1d7ea68-7d6c-11e5-8294-212649094b63.png)

The bottom half of the window should be blank when no DevCards are available.

**Comment by adrfoong** [comment]
This might not actually be a bug..

**Comment by clayellis** [comment]
@adrfoong Please determine if it is or not and then update your issue to reflect your findings by leaving an additional comment or closing the issue.
