### ISSUE TITLE
Group 2 phase 2 - Sometimes unable to buy a development card.

### ISSUE THREAD

**Issue by cache117** [cs340tabyu/CatanBugTracker#102]
I haven't identified a pattern, but sometimes, when I have resources to buy a dev card, i open up the modal to buy one, and click buy, but nothing happens.
![image](https://cloud.githubusercontent.com/assets/11652513/10798405/14336df6-7d6d-11e5-9486-949a1e870d82.png)

**Comment by clayellis** [comment]
@cache117 Please list steps to reproduce. I'm not seeing the same bug. What happens if you click again? Is it only when you click Buy Card once? Please be more specific.
