### ISSUE TITLE
Group 2 Phase 2 -- Registering doesn't check validity

### ISSUE THREAD

**Issue by liukaichi** [cs340tabyu/CatanBugTracker#104]
Even though the view updates with red, registering doesn’t check password validity or username validity -- it just registers you anyway.
![image](https://cloud.githubusercontent.com/assets/7852745/10798479/7a25dc5c-7d6d-11e5-9865-442cb38abc02.png)

**Comment by matt-hoiland** [comment]
Levi

**Comment by miarodri** [comment]
Length checking was not implemented and password checking was using a faulty regex pattern. Fixed.
