### ISSUE TITLE
Group 2 Phase 2 Sending chat from swagger under different color (Pete as blue on swagger and white in client)

### ISSUE THREAD

**Issue by theshecoder** [cs340tabyu/CatanBugTracker#105]
When using swagger to send a chat, the chat log populates the local player as a the color from swagger. 

![image](https://cloud.githubusercontent.com/assets/14060943/10798504/97038ffe-7d6d-11e5-8c9e-8ea8d0b9390e.png)

**Comment by matt-hoiland** [comment]
Joey

**Comment by matt-hoiland** [comment]
Since we discussed in class today that the server operates by Design By Contract, using swagger to inject data into a game seems to violate the contract.
