### ISSUE TITLE
Team 5 Phase 2 - Placing Robber

### ISSUE THREAD

**Issue by madisonjbrooks12** [cs340tabyu/CatanBugTracker#11]
Steps:
1. Place robber on a hex with no settlements surrounding it

Results:
The "Choose who to rob" modal comes up with a "None" player who has 0 cards

Expected results:
The "Choose who to rob" modal does not come up at all (only players with settlements surrounding the hex should come up, and if they have 0 cards, they should not come up either).

**Comment by madisonjbrooks12** [comment]
To add to this, when I place the robber on a hex with a player's settlement but the player has no resources, the same "None, 0" comes up. The player's name does not show up. (Still, the modal should not come up at all if there is nothing to rob.)

**Comment by dcox34** [comment]
This was modeled after the provided client, where it does in fact show a "None" dialog.  It'd be an easy fix, but we specifically made this to act like the client they gave us.

**Comment by madisonjbrooks12** [comment]
Oh okay, my mistake! Our team misunderstood the provided videos.

**Comment by dcox34** [comment]
No worries!
