### ISSUE TITLE
Team 6 Phase 2- Init Phase: Road should be added before Settlement (MINOR)

### ISSUE THREAD

**Issue by dnorth** [cs340tabyu/CatanBugTracker#113]
NOTE: I don't know if this should be considered a bug. However, the way the client given to us works is the way described in this issue. But it doesn't matter in the overall scheme in the game and the real rules say "Place your 2 roads and your 2 settlements on the game board." so it doesn't specify WHICH should go first.

Steps:
- Login
- Join a NEW game and Pick your color
- Start the Initialization phase

Expected Result:
- Choosing a road should be the first option

Actual Result:
- Choosing a settlement comes first

**Comment by xuther** [comment]
This is not in line with official Catan rules. See http://www.catan.com/en/download/?SoC_rv_Rules_091907.pdf
