### ISSUE TITLE
Group 2 Phase 2 - Can't Place road on edge of map

### ISSUE THREAD

**Issue by adrfoong** [cs340tabyu/CatanBugTracker#119]
![cantplaceroad](https://cloud.githubusercontent.com/assets/9939603/10799289/af3daf7e-7d71-11e5-9aa9-7e8a56bb4702.png)

Playing as brown player. Player can't place road on the edge of map, but works fine on the inside.

**Comment by matt-hoiland** [comment]
This has been corrected.
