### ISSUE TITLE
Unresponsive MaritimeTradeController.  Team 3 - Phase 2

### ISSUE THREAD

**Issue by joeynelson42** [cs340tabyu/CatanBugTracker#120]
When it isn't your turn and you select the MaritimeTrade button nothing happens.

**Comment by ramorris3** [comment]
This isn't a bug.  From the Catan rules pdf (https://students.cs.byu.edu/~cs340ta/fall2015/group_project/Catan_Rules.pdf):

"b) Maritime Trade✹
You can also trade without the other players!
**During your turn**, you can always trade at 4:1 by putting
4 identical Resource Cards back in their stack and taking any
1 Resource Card of your choice for it."

**Comment by ramorris3** [comment]
JK!!! I just read from the spec how it's supposed to bring up a Modal saying it isn't your turn when you click on the button and it's not your turn.  You're right.

**Comment by theroundball** [comment]
---

## Bug Fixed

When it is not your turn the maritime modal still pops, everything is disabled and a 'not your turn' message is displayed.

**Comment by cs340tabyu** [comment]
To clarify, the button was not disabled and no message showed when it wasn't your turn.
