### ISSUE TITLE
Team 6 Phase 2 - During setup phases, victory points show number of victory points and the number 0 right on top of each other

### ISSUE THREAD

**Issue by tgrossen** [cs340tabyu/CatanBugTracker#123]
Steps to reproduce:
1) Start or join game that hasn't gotten past setup phase
2) Place first or second settlement.

Result:
Victory point counter shows int 0 with new int (1 or 2) on top of it

Expected:
Victory point counter just shows single int

**Comment by xuther** [comment]
fixed
