### ISSUE TITLE
Can't buy road.  Team 3 - Phase 2

### ISSUE THREAD

**Issue by joeynelson42** [cs340tabyu/CatanBugTracker#125]
Occasionally when I try to buy a road and I have the correct resources it will warn me that I don't have the resources and then quickly end my turn.

**Comment by mattshurtz** [comment]
Please provide more details. under what situations does this happen?

**Comment by ramorris3** [comment]
No one on our team can reproduce this issue, so we can't fix it.  What are some specific steps to reproduce?  If we don't get more details, we're not going to treat this as a bug (per TA instruction)

**Comment by theroundball** [comment]
I have built 15 roads in a game with two local clients open:

![screen shot 2015-11-02 at 9 27 26 am](https://cloud.githubusercontent.com/assets/7108567/10887443/5edd6cdc-8144-11e5-8c31-1b3d081ee7b0.png)

As well as in a game with all AI:

![screen shot 2015-11-02 at 9 30 09 am](https://cloud.githubusercontent.com/assets/7108567/10887474/77f8f29a-8144-11e5-98ae-5d767b3afd49.png)

I built 30 roads and never had this error. 

---

## bug fixed
