### ISSUE TITLE
Team 5 Phase 2 - Domestic Trade

### ISSUE THREAD

**Issue by shampto3** [cs340tabyu/CatanBugTracker#13]
Steps Taken:
- Run the client window twice to run two different people in the same game. (You can do this by running one in debug mode, and the other in normal run mode)
- Join the same game
- Have one player offer a trade to the other player
- Have the other player reject the trade
- Have the first player offer the same trade (or different trade, it doesn't matter)

Expected Results:
- The accept overlay should only show the latest trade

Actual Results:
- The accept overlay showed two of each resource. (it stacked both trade offers)

**Comment by mwalker9** [comment]
![image](https://cloud.githubusercontent.com/assets/9952682/10777727/059fbe40-7ce4-11e5-80c3-6c4edc6e3bb4.png)

**Comment by dnorth** [comment]
This has been fixed by reseting the AcceptTradeOverlay() whenever the trade offer comes through.
