### ISSUE TITLE
Team 15 Phase 2 User can start a game as the same color as another user

### ISSUE THREAD

**Issue by mwilliammyers** [cs340tabyu/CatanBugTracker#135]
If you join the same game but stay on the color choosing modal window on multiple clients you can choose the same color and start the game because the already picked colors do not sync when you are all on the color choosing page at the same time.

**Comment by mwilliammyers** [comment]
Additionally when there are two players with the same color a user cannot start the game if they are still on the color choosing modal window. (which means the game starts with only 3 players)

**Comment by nwohlgemuth** [comment]
I'll fix this

**Comment by nwohlgemuth** [comment]
The client demo actually displays this same behavior
