### ISSUE TITLE
Team 6 Phase 2 - Development card counter doesn't populate during same turn

### ISSUE THREAD

**Issue by tgrossen** [cs340tabyu/CatanBugTracker#138]
Steps to reproduce:
1) Gain enough resources to buy a development card
2) Buy a development card

Result:
Number counters for development cards don't increment at all until next turn

Expected:
Number counter should increment for respective dev cards, in the same turn

**Comment by cjonghyun** [comment]
Fixed. Number of cards get updated during the same turn.
