### ISSUE TITLE
Team 1 Phase 2 - Can build road on water

### ISSUE THREAD

**Issue by zachanator070** [cs340tabyu/CatanBugTracker#140]
When we are prompted to build a road we can place a road sometimes on a water tile. When we click to add a road on a water tile it is not sent to the server though.

**Comment by zachanator070** [comment]
-submitted by Zach Johnson

**Comment by cache117** [comment]
Redid our algorithm, now it disallows placing on water under all circumstances (Setup Phase and normal Gameplay)
