### ISSUE TITLE
Team 6 Phase 2 - Soldier dev card button is active, even when no soldier cards are possessed

### ISSUE THREAD

**Issue by tgrossen** [cs340tabyu/CatanBugTracker#148]
Steps to reproduce:
1) Play game until at least your second turn
2) Don't buy any dev cards
3) Open dev card selector

Result:
Soldier dev card is enabled, even though the number is 0

Expected:
Soldier dev card shouldn't be enabled when the number is 0

**Comment by cjonghyun** [comment]
It is fixed. Soldier card button is active only when it's available
