### ISSUE TITLE
Team 18 Phase 2 - Can cancel road/settlement building in set up rounds

### ISSUE THREAD

**Issue by ojaneeo** [cs340tabyu/CatanBugTracker#151]
Steps
Join a new game

Results
Modal pops up to place a road, but you can cancel out of it

Expected Results
Modal pops up to place a road and YOU CAN'T ESCAPE

**Comment by ojaneeo** [comment]
Colin already logged this.

**Comment by cs340tabyu** [comment]
Duplicate with issue 62
