### ISSUE TITLE
Team 1 Phase 2 - No Winner Pop-up

### ISSUE THREAD

**Issue by jessethomson** [cs340tabyu/CatanBugTracker#152]
When you get ten points, no dialog pops up indicating you have won. (I was able to get 10 points during round 1 of the setup phase by building settlements. The points would update accordingly with each settlement I placed, but nothing happened when I got 10 points.)
-Jesse T

**Comment by theshecoder** [comment]
This bug has been resolved. When any player reaches 10 points, either the 'you win' or 'you lose' graphic is displayed on screen.
