### ISSUE TITLE
Team 1 Phase 2 - Rejoin game you are already in

### ISSUE THREAD

**Issue by jessethomson** [cs340tabyu/CatanBugTracker#157]
You can join a game that you have already joined (and are currently in) by opening up a different client and logging in with the same username/password. It also lets you pick a different color at that point so then you get logged in and your player has two colors.
-Jesse T

**Comment by longlostbro** [comment]
I can't find any documentation on what we are supposed to do here. Should we deny access to a second user?(not sure if possible) or should we make sure that the color on both clients changes to the last selected color?(I believe the demo client does this)

**Comment by theshecoder** [comment]
We have fixed this bug. You are now able to log in using another client into the same player. You are then prompted to pick a color. If you pick a color different than the first client, that client will auto update to the newest color picked on the current client. (All instances of the same client will show as the same color)
