### ISSUE TITLE
Team 1 Phase 2 - No Most Roads Icon

### ISSUE THREAD

**Issue by jessethomson** [cs340tabyu/CatanBugTracker#159]
When you have a bunch of roads, the most roads icon is never displayed. (I was able to build a TON of roads in the FirstRound of the setup phase.)
-Jesse T

**Comment by theshecoder** [comment]
Our setup phase was not working at the time we sent the code. We have now fixed this bug. You are only able to build two roads during setup phase and the most roads icon displays correctly during normal gameplay.
