### ISSUE TITLE
Team 15 Phase 2 The game gives points/road etc. to another player as well as current player

### ISSUE THREAD

**Issue by mwilliammyers** [cs340tabyu/CatanBugTracker#166]
This might be related to #135 but when a user places a road another player (not the player with the same color) gets credit for placing a road. 

If you look at the screenshot below, I placed a road as Sam but Scott also got credit for it...
![screen shot 2015-10-28 at 1 15 50 pm](https://cloud.githubusercontent.com/assets/2526129/10800224/73868140-7d76-11e5-8bd8-51a7d0f25051.png)

**Comment by mwilliammyers** [comment]
It also skipped Scott's turn...

**Comment by trialofelements** [comment]
I tried to replicate this, and I cannot. I even tried with two greens in indeces 0 and 3, the way your screenshot shows. If you can replicate it again, please tell us more about your steps.

**Comment by mwilliammyers** [comment]
Yeah I realize this is very tricky to replicate, I apologize (I don't know how it happened either). I will work on replicating it...
