### ISSUE TITLE
Team 20 Phase 2 Player Waiting stuck

### ISSUE THREAD

**Issue by andrewpk1** [cs340tabyu/CatanBugTracker#175]
When there are 3 people waiting in the player waiting screen and a 4th person joins the 4th person can join the game but the other 3 people that are waiting get stuck unless they exit out and re-join.

**Comment by cs340tabyu** [comment]
There is no team 20. Which team did you mean?

**Comment by andrewpk1** [comment]
My bad all of the team 20's should be team 10
