### ISSUE TITLE
Team 15 Phase 2 Can login as a user that is already logged in

### ISSUE THREAD

**Issue by mwilliammyers** [cs340tabyu/CatanBugTracker#177]
I couldn't find anything against this in the functional spec so I am not sure this is a bug but you can login as a user that is already logged in.

**Comment by eric-nord** [comment]
TA this doesn't count against us
Team 16 please close this issue
This is reflected in the Demo and should not be considered an issue

**Comment by mwilliammyers** [comment]
Ok we will close it, sorry.

**Comment by eric-nord** [comment]
Ha ha no worries.  Just cleaning tickets up.
