### ISSUE TITLE
Team 15 Phase 2 Host CLI parameter does not work

### ISSUE THREAD

**Issue by mwilliammyers** [cs340tabyu/CatanBugTracker#182]
Related to #181
When doing: `java -jar catan-client.jar 192.168.15.15 8081` with the server running on `localhost:8081`  the game runs fine (indicating that the client is actually running on `localhost:8081` and not attempting to run on the bogus IP address I gave it).

**Comment by nwohlgemuth** [comment]
I'll fix this
