### ISSUE TITLE
Team 16 - Phase 2 - Discard - Waiting Modal 

### ISSUE THREAD

**Issue by trialofelements** [cs340tabyu/CatanBugTracker#184]
When someone else rolls a 7 and you need to discard, after discarding, the "waiting for other players to discard" waitModal won’t go away. Different behavior if you roll the 7.

**Comment by eric-nord** [comment]
This may be resolved by changing any timers in your code from java utils timer to java swing timer - When you use the java utils timer it runs in a separate thread and causes problems.
