### ISSUE TITLE
Non-contributors cannot suggest labels

### ISSUE THREAD

**Issue by eric-nord** [cs340tabyu/CatanBugTracker#2]
Non-contributors cannot suggest labels. 
Will the whole class be contributors?

Open issue @ github: 
https://github.com/isaacs/github/issues/148

Supported by SO:
http://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner/13829505#13829505

I don't get the label option when creating this ticket.
![image](https://cloud.githubusercontent.com/assets/2634204/10751834/85b14a86-7c49-11e5-9d9b-9c7384e60a6a.png)

The "Label" text is also not clickable when trying to edit. 
![image](https://cloud.githubusercontent.com/assets/2634204/10751858/c41a52a4-7c49-11e5-8e01-69aa81bdaccc.png)

**Comment by colingm** [comment]
I also created a bug and it wouldn't allow me to add any labels

**Comment by colingm** [comment]
I also created a bug and it wouldn't allow me to add any labels @bmcgary  @cs340tabyu

**Comment by cs340tabyu** [comment]
Hello All,

As many as you know there is a slight issue with logging bugs on git hub! You can't select/assign the labels! (This is my mistake, sorry guys!) SO to fix this we have a work around/hack/fix call it what you will. When you log a bug you have to give it a title and a comment. In either the comment or the title please put the name of the team you are grading (eg: Team 20) and phase (eg: Phase 2). Then you can search for your team by searching "Team 20 Phase 2". If you have already logged bugs please go back and edit them to have both the team and phase included.
Again that is for every bug you find, when you go to log it in the Github issues, somewhere you need to put the phase and team number that you are grading. Thank you!
