### ISSUE TITLE
Team 15 Phase 2 - No option to do a 2:1 trade

### ISSUE THREAD

**Issue by alecfullofmer** [cs340tabyu/CatanBugTracker#207]
I had a settlement built on a 2:1 wood port, had three wood resources. When I clicked on the Maritime Trade button, there was no option to do a 2:1 trade.

**Comment by enottinger** [comment]
I could not reproduce this error. Could you specify the exact sequence of events or give a screenshot?

**Comment by alecfullofmer** [comment]
My teammate couldn't replicate it either so I closed it. Must have been a
gui thing.
