### ISSUE TITLE
Team 13 Phase 2 - Trade freezes in game with all AI players

### ISSUE THREAD

**Issue by austindh** [cs340tabyu/CatanBugTracker#209]
Start a new game with all AI players. Once you have resources, try to do a domestic trade.  When you have selected resources to send and receive, click the trade button. You get stuck on the "Waiting for Trade to Go Through") screen. In the demo, the AI players will immediately accept or reject the trade and you won't even see the waiting screen.

**Comment by matthew57** [comment]
This is not a bug with the AI. If it wasn't implemented then the button for adding an AI should have been disabled: Status Minor bug.
