### ISSUE TITLE
Window doesn't adjust to smaller screens Team 3 - Phase 2

### ISSUE THREAD

**Issue by joeynelson42** [cs340tabyu/CatanBugTracker#217]
When opening the client on smaller screens (i.e. 11-inch laptop) the login overlay is inaccessible.

**Comment by mattshurtz** [comment]
This is a view issue, not a controller issue. In other words, not our problem.

**Comment by japhib** [comment]
Are you able to adjust the TA's version of the client for your screen? I wasn't able to and neither was anyone on our team. I'm really curious why this was logged as a bug.

**Comment by theroundball** [comment]
---

## Bug Fixed

TAs said that this is not an issue we should fix.
