### ISSUE TITLE
Team 15 - Phase 2 - Maritime Trade Get Resource

### ISSUE THREAD

**Issue by alexcandrews** [cs340tabyu/CatanBugTracker#219]
When performing a 4:1 maritime trade; user can select the the Resource to Give, but the resource to Get is not shown graphically.
![settler s of catan test - maritime trade](https://cloud.githubusercontent.com/assets/4567626/10805475/887d1ff6-7d93-11e5-85ce-022f45df589d.png)
It should look, like on page 25 of the functional spec where the Maritime Trade Get Resource is clearly identified.
But to verify; the trade IS indeed made.

**Comment by eric-nord** [comment]
Yeah the designer in me thought this was a better flow - You only ever get 1 and so showing the get resource and being able to reset it is pointless - I should have stuck to the spec. I'll get it updated.

**Comment by alexcandrews** [comment]
That's fair. And I even think I agree with your design choice.

However, I still wish that upon selecting the ResourceType to GET, that the other ResourceType icons would be disabled. Or basically, I wish somehow it would highlight to the user WHICH ResourceType they would be receiving. Does that make sense?

**Comment by eric-nord** [comment]
4 sure. I thought there was an outline on the one selected but it might be
different on my computer.

**Comment by alexcandrews** [comment]
Gotcha. Ya I didn't see an outline. But I do think that would be a good solution.
