### ISSUE TITLE
Can MaritimeTrade resource for itself Phase 2 - Team 3

### ISSUE THREAD

**Issue by joeynelson42** [cs340tabyu/CatanBugTracker#223]
In maritimeTrade it allows you to trade a resource, for that very same resource, e.g. 4 wood for 1 wood.

**Comment by mattshurtz** [comment]
Not a bug. This is allowed on the TA's client and there is no rule in the specs for this. Please find me a reference otherwise.

**Comment by theroundball** [comment]
---

## Bug Fixed

TA Client allows it. 
Specs say, 'Any player can do a 4:1 trade of any kind of resource.' and does not specify you have to trade for a different resource. 

This strategically makes sense if a player wants to get rid of cards to avoid discarding on a 7.
