### ISSUE TITLE
Team 17 Phase 2 New Game doesn't show up for everyone

### ISSUE THREAD

**Issue by ghost** [cs340tabyu/CatanBugTracker#228]
New games don't show up properly.

Steps to duplicate:
1) Open two clients
2) Login to both as different people
3) Create a new game in one client

Expected Result: New game should show up on both clients.

Actual Result: New game only shows up in the client that made it. You can either close the client and reopen it or make your own new game to refresh the GameInfo list. This is probably not super important but its functionality that exists in the demo client that doesn't in your client.

**Comment by colingm** [comment]
Fixed in commit #e2ccaac
