### ISSUE TITLE
Team 17 Phase 2 - Two players can have the same color

### ISSUE THREAD

**Issue by joshnelson7** [cs340tabyu/CatanBugTracker#232]
Steps to duplicate -
1. Log in to client 
2. Create a game and leave the client open
3. Have someone else log in to a client, join the game,
 and select a color
4. Rejoin the game from the first client
5. You will be able to select the color the other player chose
![samecolor](https://cloud.githubusercontent.com/assets/5407015/10806998/8a096a02-7da0-11e5-896b-36b88123eb60.PNG)

**Comment by colingm** [comment]
Fixed in commit #e2ccaac
