### ISSUE TITLE
Team 3 Phase 2 - Cannot add AI players

### ISSUE THREAD

**Issue by clayellis** [cs340tabyu/CatanBugTracker#24]
You should be able to add AI players at the beginning of the game if the game is not already full.

Steps to reproduce:
- Log in
- Create a new game
- Join the game
- _Should be able to add AI now_

**Comment by mattshurtz** [comment]
This is a duplicate: Team 3 Phase 2 - Client Hangs on Joining Empty Game #41

**Comment by clayellis** [comment]
I'll close the issue then.
