### ISSUE TITLE
Team 17 Phase 2 - Roads can be built across enemy settlements

### ISSUE THREAD

**Issue by Jeutnarg** [cs340tabyu/CatanBugTracker#250]
The picture and link should explain it.

http://www.catan.com/faq/4624-roads-may-roads-i-build-go-through-other-players-settlements-and-cities

![can t build through other players settlements](https://cloud.githubusercontent.com/assets/8787057/10807743/a4950b12-7da8-11e5-9d6f-becedba88e13.PNG)

**Comment by colingm** [comment]
fixed
