### ISSUE TITLE
Team 17 Phase 2 - Registration form allows illegal names

### ISSUE THREAD

**Issue by joshnelson7** [cs340tabyu/CatanBugTracker#255]
The form does validate the length correctly, but allows characters other than letters, digits, underscores, and dashes in the username field.
![names](https://cloud.githubusercontent.com/assets/5407015/10808037/7135a5de-7dac-11e5-8d36-c6bb53be7a7f.PNG)

**Comment by colingm** [comment]
I think there is only character requirements for the password according to the spec, can you check if it allows you to put weird characters in the password?

**Comment by colingm** [comment]
Fixed in commit #6030595
