### ISSUE TITLE
Team 17 Phase 2 - Join game - select color box shows disabled colors from previously viewed game

### ISSUE THREAD

**Issue by joshnelson7** [cs340tabyu/CatanBugTracker#263]
1. Log in
2. Create a new game
3. on the game hub modal, click rejoin on a game with existing players
4. Notice the disabled colors
5. Click cancel to exit the color select modal
6. Click rejoin on the new game you created
7. The color select box will show the same colors disabled from the previously viewed game, even though the new game should have no colors selected.
8. The only way that I have found to reset the colors to enabled is to close the client and reopen it.

Note: The effect is cumulative.  Every time you click join or rejoin on a game the disabled colors include all disabled colors from previously viewed games.  This means that if you have viewed games with all colors disabled you will not be able to select a color or join any game.  Screenshot below.
![allcolorsdisabled](https://cloud.githubusercontent.com/assets/5407015/10808551/62178f1c-7db2-11e5-884f-07859ef6cec1.PNG)

**Comment by colingm** [comment]
Fixed in commit #fd49a37
