### ISSUE TITLE
Team 18 Phase 2 - Unable to buy dev card

### ISSUE THREAD

**Issue by colingm** [cs340tabyu/CatanBugTracker#27]
Steps:
- Log in as Pete
- Have the resources necessary to buy a development card
- During your turn click the button to open the buy dev card menu
- Click "Buy Card"

Results:
- The menu closes and your resources are not deducted, the stack trace from below appears in the server logs, the card is not bought

Expected Results:
- The card is successfully bought and your resources are deducted properly

Server Stack Trace:
INFO: {"type":"buyDevCard","playerIndex":10}
     [java] com.google.gson.JsonParseException: 'playerIndex' field has an inval
id value.
     [java]     at dy.a(Unknown Source)
     [java]     at dy.deserialize(Unknown Source)

**Comment by jordantgates** [comment]
Fixed
