### ISSUE TITLE
Team 17 Phase 2 Sometimes can roll twice

### ISSUE THREAD

**Issue by ghost** [cs340tabyu/CatanBugTracker#274]
This one will be harder to fix.  I don't really know how to duplicate it.  I wouldn't even report it except that it has happened twice. Anyway the dialog rolled for me and I clicked okay and then it rolled again immediately.  The screenshot shows in the game history that I rolled twice in a row.  
![bug](https://cloud.githubusercontent.com/assets/1058894/10808728/29e9847c-7db4-11e5-8a8b-c6f9f76cbf57.PNG)

**Comment by colingm** [comment]
Fixed in commit #e623478
