### ISSUE TITLE
Team 17 Phase 2 Passwords don't match

### ISSUE THREAD

**Issue by ghost** [cs340tabyu/CatanBugTracker#275]
When passwords don't match it should say they don't match

Steps to dup:
Register a user and make the passwords different

Expected: A popup should say that the passwords don't match
Actual: A popup says the password is invalid

This may not be a bug, but it is different than the demo client

The demo looks like this when this happens:
![should](https://cloud.githubusercontent.com/assets/1058894/10808802/04062d04-7db5-11e5-808d-8717b22c801f.PNG)

Your client looks like this:
![yours](https://cloud.githubusercontent.com/assets/1058894/10808803/075d6954-7db5-11e5-9ed4-28194d3428db.PNG)

**Comment by colingm** [comment]
Fixed in commit #6030595
