### ISSUE TITLE
Team 17 Phase 2 Login fails

### ISSUE THREAD

**Issue by ghost** [cs340tabyu/CatanBugTracker#278]
If the server is turned off (simulating a broken server) and you try to login the message displays saying that you typed a bad password or username.  I used a real username but it threw a server exception.  This should say something else like login failed or server error.  The demo client says "Sign in failed"

**Comment by colingm** [comment]
Fixed in commit #ecab958

**Comment by colingm** [comment]
Fixed in commit #6030595
