### ISSUE TITLE
Team 4 Phase 2 - Can Maritime Trade for the same resource

### ISSUE THREAD

**Issue by sebrantley** [cs340tabyu/CatanBugTracker#279]
When maritime trading. It is possible to, for example, select to trade sheep. and then select to receive sheep.  Im honestly not 100% sure if this is a bug or just a very strange game option. 

Before Trading: Have 4 total sheep resources
![image](https://cloud.githubusercontent.com/assets/13441798/10808968/e3ff8ba2-7db6-11e5-9822-dbb76f5af3c4.png)

After Trading: Only 1 sheep remaining
![image](https://cloud.githubusercontent.com/assets/13441798/10808992/4565247e-7db7-11e5-951d-3bed07863a5a.png)

**Comment by mattshurtz** [comment]
not a bug
