### ISSUE TITLE
Team 17 Phase 2 - Client Freezing

### ISSUE THREAD

**Issue by phelpsdb** [cs340tabyu/CatanBugTracker#285]
During a game session the client would sometimes become completely unresponsive and would have to be restarted to continue the game. The client would freeze during the respective player's turn after a modal dialog would close. All buttons, scrollbars, and other UI elements were still in an enabled state, but could not be clicked (even after resizing the window). It is difficult to reproduce this bug, and we thought it may have been a fluke, except it occurred three times between two computers during the course of a game. I apologize that we could not find any reliable steps to reproduce this bug.

**Comment by colingm** [comment]
Fixed in commit #e623478
