### ISSUE TITLE
Team 3 Phase 2 - Color Selector Modal Does Not Update

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#29]
On color selector screen, does not update when other players switch color.

To reproduce:
join game
wait on color selector screen. 
Using swagger, join the game with a different user and choose a different color than that user had before. 
**Color selector does not update.**

**Comment by mattshurtz** [comment]
---

## Bug Fixed

if you click on a color that someone else just joined a game with it will disable teh button and you have to select another one.
