### ISSUE TITLE
Team 5 Phase 2 - Re-choose color

### ISSUE THREAD

**Issue by lauracharlotte** [cs340tabyu/CatanBugTracker#298]
Steps:
Exit out of game while playing. 
Open up game again.
Rejoin Game. 
Actual Result:
Lets you re-choose your color in the game.
Expected Result:
Have the same color as before

**Comment by tkwilli94** [comment]
In the provided client that we were given as a demo, you are allowed to change colors when you rejoin a game. We specifically modeled our client after that.

**Comment by cs340tabyu** [comment]
Players should be allowed to change their colors if re-joining a game. (Functional Specs page 5)
