### ISSUE TITLE
Team 5 Phase 2 - Blank trade offer

### ISSUE THREAD

**Issue by lauracharlotte** [cs340tabyu/CatanBugTracker#300]
Steps:
Be playing with 2 players
Do a domestic trade request
Offer something and ask to receive something

Expected: 
Opposite player gets a message asking to trade with a pictures of items wanting to trade

Actual:
The item being offered to trade is blank and therefore player does not know what they getting from the trade (the item from the person wanting to trade shows, or the first item is blank the second item shows the picture of the item)

*sorry I would put a picture but it is not pasting the image when I try

**Comment by dnorth** [comment]
Whenever I receive a trade offer I can always see the images. Are there more specific steps you took to reproduce this error?

**Comment by cs340tabyu** [comment]
It sounds like this issue only showed up on lab computers, correct?
