### ISSUE TITLE
Team 17 Phase 2 - Player Color Doesn't Fully Update on Re-Join 

### ISSUE THREAD

**Issue by phelpsdb** [cs340tabyu/CatanBugTracker#302]
Steps to reproduce: While playing a game in one client, open a second client and log in as the same person. Join the same game, but as a different color. In the first client, the TurnTrackerView in the bottom left corner of the first client will update the color properly, but the top bar will remain the old color.

It's not a major bug, but I believe a fix is possible by simply updating the view's local player color.

**Comment by colingm** [comment]
Fixed in commit #6030595
