### ISSUE TITLE
Team 17 Phase 2 - Incorrect Log Color for Computer Player

### ISSUE THREAD

**Issue by phelpsdb** [cs340tabyu/CatanBugTracker#308]
When trading with a human player, if the receiving player rejects a trade offer, a log message is displayed in the receiver's color. When trading with a computer player, however, the same log message is displayed in the sender's color instead of the receiver's color. Should the "trade was not accepted" log message always be in the color of the player who rejected it, or else always in the color of the sender? Either way, maybe it should be consistent between human and computer players.

**Comment by colingm** [comment]
Investigated to be a problem with the server, the demo client has the same problem. The server assigns the source of the message as the human player when a trade is offered to a computer player.
