### ISSUE TITLE
Group 15 Phase 2 Player waiting controller bug

### ISSUE THREAD

**Issue by bmatthew123** [cs340tabyu/CatanBugTracker#31]
The player waiting controller is set properly for the person joining, but the people who had previously joined do not see the other player's names appear on their screen. (The number of remaining players does get updated appropriately) Also, adding AI players has the same effect.

**Comment by bmatthew123** [comment]
Accidentally closed trying to add labels...

**Comment by nwohlgemuth** [comment]
This issue can be circumvented by resizing the player waiting window manually
