### ISSUE TITLE
Team 3 Phase 2 - RollView modal is not displayed

### ISSUE THREAD

**Issue by matt-hoiland** [cs340tabyu/CatanBugTracker#32]
Auto rolling is functional, but when required to roll the the roll modal is not displayed.

**Comment by japhib** [comment]
We're not sure when this is happening. We've tried to test this a bunch and we can't get it to happen. We did, however, fix a thing where closeModal() was getting called rampantly, and it could very well have been the problem.

**Comment by theroundball** [comment]
## This was fixed when we changed our close modal to only close modals that are showing?

## bug fixed
