### ISSUE TITLE
Team 3 Phase 2 - Two players allowed same color

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#34]
To reproduce:

Log in and join a game
On the color selector screen, choose a free color.
Using a different instance of the client (or swagger), log in with a different user and join the same game
On the color selector screen, choose the same color.
Join game with both players (order irrelevant)
**Both players have the same color**
![screenshot 2015-10-27 19 36 45](https://cloud.githubusercontent.com/assets/14239472/10777574/83bfdf00-7ce2-11e5-9cba-b082086278c4.png)

**Comment by mattshurtz** [comment]
This is a duplicate bug: Team 3 Phase 2 - Color Selector Modal Does Not Update #29. The actual allowing is done on the server side (not our problem), but the updating of color selector is a bug. Thus these two are the same bug.

**Comment by theroundball** [comment]
## It now won't let you join game on a color that has already been chosen. When you move to pick a different color the color that has been already chosen is disabled. 

## bug fixed
