### ISSUE TITLE
Team 16 - Phase 3 - First Round Setup out of turn

### ISSUE THREAD

**Issue by ojaneeo** [cs340tabyu/CatanBugTracker#346]
Steps to Reproduce:
1. Log in as Josh
2. Join first game (default)

Expected Result
Josh will wait for Zack to place his initial road and settlement

Actual Result
Josh is prompted to place initial road and settlement in Zack's colors. Once this is done, everyone is in a player waiting state, and the game is STUCK FOREVER. (Note the "player waiting" button on all 4 clients)
<img width="1675" alt="screen shot 2015-11-19 at 11 33 35 am" src="https://cloud.githubusercontent.com/assets/12422194/11280269/75a1fc8c-8eb2-11e5-913f-f2254a769279.png">

**Comment by colingm** [comment]
Here is a screenshot of it trying to make Emily place Colin's road
![image](https://cloud.githubusercontent.com/assets/11670266/11290520/d8149efa-8ef4-11e5-834d-84f1bf2b7976.png)
