### ISSUE TITLE
Team 18 Phase 2 - Able to select more resources to discard than needed

### ISSUE THREAD

**Issue by colingm** [cs340tabyu/CatanBugTracker#35]
Steps:
- Have more than 7 cards when someone rolls a 7
- Begin to choose the resources to discard
- After selecting enough cards continue to add more cards

Result:
- The game allows you to select more cards than you have to discard and actually discards all of them

Expected Result:
- After selecting enough cards it should not let you discard more than needed by disabling all of the up buttons

![image](https://cloud.githubusercontent.com/assets/11670266/10777547/46080944-7ce2-11e5-900a-d5b001f6a692.png)

**Comment by jordantgates** [comment]
Fixed, should close
