### ISSUE TITLE
Team 3 Phase 2 - Asks to place settlement before road

### ISSUE THREAD

**Issue by clayellis** [cs340tabyu/CatanBugTracker#38]
When beginning a new game and entering Round 1 the game asks the player to place a settlement first when it should ask the player to ask a road first. 

_I realize the real-life Catan game requires a settlement before a road, but the functional specifications specify ;) the following:_ **On a player’s turn, the “place road” overlay should appear. When a player places a road, it should close the modal and update the map. Then the “place settlement” overlay should appear... Functional Spec - pg. 7**

**Comment by mattshurtz** [comment]
Asked TA during implementation. Said this is ok.

**Comment by theroundball** [comment]
---

## Bug Fixed

**Comment by clayellis** [comment]
Cool! I'll close the issue then.
