### ISSUE TITLE
Team 16 Phase 3 - Game Hub distorted

### ISSUE THREAD

**Issue by jaredcrystal** [cs340tabyu/CatanBugTracker#381]
steps to reproduce:
1. register as a new user

Here is how the game hub looks for me:

![image](https://cloud.githubusercontent.com/assets/14153009/11289200/c503d2ca-8ee7-11e5-8e9b-5cfd40b3ed23.png)

**Comment by colingm** [comment]
Happened when joining as any user for me and was still distorted like this after creating a game
