### ISSUE TITLE
Team 16 Phase 3 - No ports on map for 4th player

### ISSUE THREAD

**Issue by jaredcrystal** [cs340tabyu/CatanBugTracker#383]
steps to reproduce:
1. register as four new users
2. create and join the game with all four
(3. noticed after first road placed in setup round)

Note: this is only for the fourth player:

![image](https://cloud.githubusercontent.com/assets/14153009/11289331/f5154808-8ee8-11e5-9119-a549dc3b55d1.png)

**Comment by colingm** [comment]
They never seem to appear for the 4th player even after closing the client and opening it again
