### ISSUE TITLE
Team 18 Phase 2 - Adding AI problems

### ISSUE THREAD

**Issue by Harrismc** [cs340tabyu/CatanBugTracker#39]
After i place a road and settlement, am given option to add AI players. At first clicking the add button doesn't seem to do anything, but after a few clicks the modal disappeared. I then clicked the turn button, which ended my turn and suddenly the view updated with AI players showed up and am on my next turn.

**Comment by ojaneeo** [comment]
Road and settlement placing shouldn't even happen until there are 4 players in the game
