### ISSUE TITLE
Team 9 Phase 3 - The first player to roll can not end their turn

### ISSUE THREAD

**Issue by Jon-Francis** [cs340tabyu/CatanBugTracker#390]
After a player has rolled and completed their first turn, the turn status button says 'Finish Turn!' but cannot be clicked and the turn never ends even if the game is left and later resumed.

*update to this: The Finish Turn! button only freezes after an automatic roll at the end of a countdown. If I click the roll button before time expires, I can proceed with the game

**Comment by andrewpk1** [comment]
Fixed
