### ISSUE TITLE
Team 9 Phase 3 - Player victory points not updated correctly

### ISSUE THREAD

**Issue by Jon-Francis** [cs340tabyu/CatanBugTracker#396]
<img width="1351" alt="screen shot 2015-11-19 at 7 37 24 pm" src="https://cloud.githubusercontent.com/assets/15368064/11290554/21419e84-8ef5-11e5-8155-1501f197bccf.png">
After placing two roads and two settlements and finishing a players second turn, the victory point view only shows one victory point. This is likely because the game has frozen. I also cannot scroll the game history at this point.

**Comment by darin-costello** [comment]
Fixed
