### ISSUE TITLE
Team 5 Phase 2 - Multiple Soldier Cards

### ISSUE THREAD

**Issue by shampto3** [cs340tabyu/CatanBugTracker#40]
Steps:
- Get at least 2 soldier cards.
- You can't have bought either cards on the turn you play it.
- Play one soldier card (move the robber)
- Play another soldier card

Expected Results:
- Playing any other development cards after having already played one should be disabled.
- This includes soldiers. 

Actual Results:
- I was able to play two soldier cards on the same turn. (In fact, I played three on the same turn)

**Comment by shampto3** [comment]
It looks like all development cards are having this same problem. I should only be able to play one development card per turn.

**Comment by tgrossen** [comment]
Fixed. DevCards now always are enabled/disabled when they should be.
