### ISSUE TITLE
Team 5 Phase 3 - Trade Overlay does not show when a player receives a trade offer and does not have enough resources for the trade.

### ISSUE THREAD

**Issue by cjonghyun** [cs340tabyu/CatanBugTracker#409]
When someone offers a trade to the player and if the player does not have enough resources to accept the trade, it does not show any overlay for the player who receives the trade and the overlay of the player who offers the trade gets closed and nothing happens.

<img width="574" alt="screen shot 2015-11-20 at 8 36 06 am" src="https://cloud.githubusercontent.com/assets/12752124/11303760/cce6ae02-8f61-11e5-9a99-19b29b75c2c7.png">

It should show an overlay like this.

**Comment by dnorth** [comment]
Fixed
