### ISSUE TITLE
Team 3 Phase 2 - Client Hangs on Joining Empty Game

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#41]
To reproduce:

Log in and join an empty game.
Select Color and join game.
**Player waiting modal never shown**
![screenshot 2015-10-27 19 47 33](https://cloud.githubusercontent.com/assets/14239472/10777690/965ebbda-7ce3-11e5-892d-09cc2f74bfb5.png)

**Comment by theroundball** [comment]
---

## Bug Fixed
