### ISSUE TITLE
Team 7 - Phase 3 -- cannot join game

### ISSUE THREAD

**Issue by theshecoder** [cs340tabyu/CatanBugTracker#433]
After registering a user and creating a new game, I am able to click on my player's color but nothing occurs after that. The game is never joined.

**Comment by cache117** [comment]
Here is some additional info:
![image](https://cloud.githubusercontent.com/assets/11652513/11309593/f487859c-8f81-11e5-966c-13001f5f6788.png)

**Comment by theshecoder** [comment]
[java] WARNING: Sign in failed.
[java] cn: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1

This is shown when you run your server with the TA client.
