### ISSUE TITLE
Team 18 Phase 2 - Turn tracker shows partial colors if someone changes their color

### ISSUE THREAD

**Issue by colingm** [cs340tabyu/CatanBugTracker#45]
Steps:
- Join a game as someone
- Open separate client and join as someone else but with a different color from what they originally had

Results:
- The turn tracker partially updates to show a weird combination of colors

Expected Results:
- The turn tracker should show the correct new color

To be honest I think this might be a problem with view code but I wanted to let you be aware of it
![image](https://cloud.githubusercontent.com/assets/11670266/10777724/fe997168-7ce3-11e5-987f-9192c9503188.png)

**Comment by ojaneeo** [comment]
Similarly, the points when they update draw on top of themselves, making them illegible. 
![image](https://cloud.githubusercontent.com/assets/12422194/10801988/ad93b0ca-7d7f-11e5-9eac-05f14b1b4caf.png)

**Comment by jordantgates** [comment]
Looked through code, could not see how controller could fix this, close if accurate
