### ISSUE TITLE
Team 4 Phase 3 - Cannot Register 3 Letter Usernames

### ISSUE THREAD

**Issue by dnorth** [cs340tabyu/CatanBugTracker#450]
Steps:
- Attempt to register with "Sam" or "Dan" as the username (or any 3 letter username) and any password

Expected Results:
- I am logged in as "Sam" or "Dan".  (GUI specifies "The username must be between three and seven characters" )

Actual Results:
- Given an "Invalid Input: Bad username or password combination" error

[NOTE: This also works for passwords of length 3 or less but the username is more than 3 characters]

**Comment by ramorris3** [comment]
I'm having a hard time reproducing this.  Are you using the TA client or our client?  Also, can you tell me how you are running the server and the client?  I assume you're clicking on the Jar's right?

**Comment by dnorth** [comment]
I apologize, this is not a bug. I based this off of the given AI "Sam" with his password "sam". However, it is stated in the password box that "A password must be FIVE or more characters", I did not see this before because the screen that I was using was smaller than a certain size and the client doesn't work properly with my screen. However on the new screen my error is clear. Sorry!
