### ISSUE TITLE
Team 15 Phase 3 Place robber before all players discard

### ISSUE THREAD

**Issue by some1awesome** [cs340tabyu/CatanBugTracker#454]
I was playing a game against myself and one of the purple player rolled a 7.  This made yellow and green have to discard because they had too many cards.  I discarded with yellow and when I did it the waiting for player dialog in orange and purple went away.  This allowed me to place the robber before green had finished discarding.
![robbermove](https://cloud.githubusercontent.com/assets/14840143/11310657/3dc1e616-8f88-11e5-9982-c907b1528a9a.PNG)

**Comment by eric-nord** [comment]
Resolved
