### ISSUE TITLE
Team 3 Phase 2 - Multiple clicks required to place pieces

### ISSUE THREAD

**Issue by matt-hoiland** [cs340tabyu/CatanBugTracker#46]
When building roads, settlements, and cities and placing the robber, multiple clicks are required to dismiss modal.  It is possible multiple modals are being layered.

**Comment by theroundball** [comment]
---

## I can't reproduce

**Comment by mattshurtz** [comment]
tried with multiple human clients. then tried with just ai. played a full game with both. unable to reproduce. could this be specific to your computer?
