### ISSUE TITLE
Team 3 Phase 2 - "Waiting for Trade" modal is never dismissed

### ISSUE THREAD

**Issue by clayellis** [cs340tabyu/CatanBugTracker#47]
After sending a trade, the "Waiting for Trade to Go Through" modal is never dismissed even though the Game History shows that the trade was not accepted. _See Image_ This prevents gameplay from continuing.

<img width="1354" alt="screen shot 2015-10-27 at 7 47 33 pm" src="https://cloud.githubusercontent.com/assets/10712068/10777737/26ac8d52-7ce4-11e5-9519-de5d00bf6e2d.png">

**Comment by theroundball** [comment]
How did you create this situation? did you have two clients open? Separate computers? I can't produce this error.

**Comment by theroundball** [comment]
## This was fixed by checking if the modal is already showing before showing it. 

## bug fixed
