### ISSUE TITLE
Team 3 Phase 3 - Robber Overlay

### ISSUE THREAD

**Issue by shampto3** [cs340tabyu/CatanBugTracker#484]
This one could just be a problem with the GUI and not your fault, I'm not sure.

I rolled a 7 and the place robber overlay didn't show up. My main GUI says "place the robber" and the log says that I rolled a 7, but no overlay is showing so I'm stuck doing nothing.

This could be hard to debug though since it seemed to work every other time.

<img width="664" alt="no_robber_error" src="https://cloud.githubusercontent.com/assets/8238593/11312744/67e091ce-8f95-11e5-9bf6-25cce5fe1c42.png">

**Comment by ramorris3** [comment]
I'm trying to reproduce this but not having any luck..  Were you using our client or the TA's client when this happened?
