### ISSUE TITLE
Team 3 Phase 3 - Playing 2 Dev Cards with Monument

### ISSUE THREAD

**Issue by shampto3** [cs340tabyu/CatanBugTracker#487]
Steps:
- Buy a monument card
- Buy another development card (I bought a monopoly card)
- Make it a turn where you can play either
- Play your monument card

Expected Results:
- After playing your monument card, you shouldn't be able to play any more development cards.
- This is according to <a href="https://students.cs.byu.edu/~cs340ta/fall2015/group_project/Functional_Spec.pdf">The Functional Spec</a>. You could probably argue otherwise because the functional spec can be kind of lame sometimes.

Actual Results:
- After playing the monument card I was able to play my monopoly card on the same turn.

**Comment by mattshurtz** [comment]
We did consider this scenario and built to allow as many monument cards to be played in a given turn, and not have it count towards the one dev card limit. After reviewing the functional specs I can understand how it could work the other way.

**Comment by mattshurtz** [comment]
fixed
