### ISSUE TITLE
Team 1 Phase 3 - Unable to join newly created game (Unexpected EOF from server)

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#488]
After creating a game, trying to join the game fails. Attached is a screenshot from the demo client. This same error occurs using any client (Team 1, ours, demo....)

The error appears to occur due to a socket exception due to an unexpected EOF from the server.
![screenshot 2015-11-20 15 12 41](https://cloud.githubusercontent.com/assets/14239472/11313313/29835d54-8f99-11e5-98cd-de2143752fd1.png)

![screenshot 2015-11-20 15 10 03](https://cloud.githubusercontent.com/assets/14239472/11313265/cecf7294-8f98-11e5-8067-9864881514ac.png)

**Comment by liukaichi** [comment]
bug fixed
