### ISSUE TITLE
Team 18 Phase 2 - Last player to discard doesn't lose their "Waiting For Other Players" modal

### ISSUE THREAD

**Issue by colingm** [cs340tabyu/CatanBugTracker#49]
Steps:
- Have more than 7 cards
- Have another player roll a 7
- Discard cards

Result:
- Even if you are the last one to discard you get a "Waiting for Other Players" modal on your screen that doesn't go away. Play continues for other players and your modal doesn't go away until you roll next. At that point it will disappear but your rolling modal will not pop up and the game is unplayable.

Expected Result:
- You are not stuck waiting and play continues as normal

**Comment by jordantgates** [comment]
Fixed, please close
