### ISSUE TITLE
Team 5 Phase 2 - Color picking

### ISSUE THREAD

**Issue by mwalker9** [cs340tabyu/CatanBugTracker#50]
Steps:
1) Get two different clients open
2) Login under different usernames
3) Create a new game with one of the clients
4) Join the game with that client with a color that is not red
5) Go to join game with the other client
Result:

![image](https://cloud.githubusercontent.com/assets/9952682/10777771/8ec67556-7ce4-11e5-932b-572ff4827085.png)

You can join the game with the same color under a different user, but cannot join with the color red.

Expected result:
You can join the game with any color except yellow (in this case where I chose yellow)

Similarly, if I add a few AIs, I can also choose the same color as one the AIs

![image](https://cloud.githubusercontent.com/assets/9952682/10777796/d4270ab6-7ce4-11e5-8aa4-579990a4c5c9.png)

**Comment by tkwilli94** [comment]
We were playing around with the demo client and are fairly confident that our client works the same as the given one. We were able to get two players to have the same color on the given client, and therefore didn't feel like this was a bug we actually needed to worry about.

**Comment by cs340tabyu** [comment]
If you poll at a faster rate it should minimize the issue, however the error is in the design of the code given.
