### ISSUE TITLE
Team 9 - Phase 3 My Last Bug Report

### ISSUE THREAD

**Issue by NarkoPraxis** [cs340tabyu/CatanBugTracker#509]
I've logged enough bugs, you know the code doesn't work very well.

FIX IT.

![1 x-hdeaiglxhbl3lqvm_h2g](https://cloud.githubusercontent.com/assets/11724911/11314352/0b07067e-8fa2-11e5-9c02-7d4af0a0c04e.gif)

![tumblr_inline_n30ck1betg1s0u9u5](https://cloud.githubusercontent.com/assets/11724911/11314006/cec39ae0-8f9e-11e5-9ba4-92a7a5106a37.gif)

**Comment by darin-costello** [comment]
What?

**Comment by NarkoPraxis** [comment]
those gifs are payback for your unicode bug in the last phase. 
bwahahahahahahahah
