### ISSUE TITLE
Team 3 Phase 3 Road Building in Setup

### ISSUE THREAD

**Issue by mwalker9** [cs340tabyu/CatanBugTracker#512]
Steps:
Open 4 TA clients
Login on all four by registering new users
Create new game
All join same game
In setup, it will ask to build a road--
Place a road somewhere. 
Result: 
The road doesn't show up so there is nowhere you can place the next settlement.
However, in the log it still says player\* "built a road".
Cannot continue the game using the TA client.
![image](https://cloud.githubusercontent.com/assets/9952682/11314286/61bc24a0-8fa1-11e5-9070-1518d73cb55e.png)

**Comment by mattshurtz** [comment]
Matt (the TA) said that because we implemented (with permission from the TAs) to play settlement then road in phase 2, that the problems with the TA client in setup mode is not considered a bug. Setup works fine in our client. NOT A BUG.
