### ISSUE TITLE
Team 3 Phase 3 Empty Trade

### ISSUE THREAD

**Issue by mwalker9** [cs340tabyu/CatanBugTracker#513]
Using team 3's implemented client,
Steps:
Offer a trade and ask for nothing in return
Result:
Trade goes through and other player can accept
Expected result:
Trade doesn't go through
![image](https://cloud.githubusercontent.com/assets/9952682/11314262/357fd0e4-8fa1-11e5-94d7-69d71c6915f4.png)

**Comment by mattshurtz** [comment]
Functional specs nor game rules specify saying that a trade can not be one-sided. Although the TA's client does not allow it, TA's have given the ok for this type of trading, especially since it is not specified in the specs or rules. NOT A BUG
