### ISSUE TITLE
Team 3 Phase 3 Game List doesn't update

### ISSUE THREAD

**Issue by mwalker9** [cs340tabyu/CatanBugTracker#514]
Open 4 of own clients
Login to all of them
create a game in one of them
Result:
game only shows up in one of the clients
Expected result:
game shows up on all of them
![image](https://cloud.githubusercontent.com/assets/9952682/11314320/b3654ae8-8fa1-11e5-8549-4105e93f4aaf.png)

**Comment by mattshurtz** [comment]
Technical specs does not specify this scenario. We show all current games at time of login. In Phase 1 we are to implement a poller for the model, not for the games list. (Difference as specified on swagger. games/list vs game/model). Model does not include information from the gamehub, thus it should not update all of those screens. NOT A BUG
