### ISSUE TITLE
Team 3 Phase 3 Exception Being Thrown in Client (Maybe a bug?)

### ISSUE THREAD

**Issue by mwalker9** [cs340tabyu/CatanBugTracker#515]
I don't know if this is a bug, but I wanted to let you know in case it was an issue for you.  When I tried registering with a username that already existed, the gui responded appropriately but this is what showed up in the terminal and it didn't look good:
![image](https://cloud.githubusercontent.com/assets/9952682/11314362/2e0501c6-8fa2-11e5-9dd1-e80ad46f0abb.png)

Just wanted to let you know

**Comment by mattshurtz** [comment]
Exceptions that do not hamper game play do are not bugs. The client is just reporting a 400, bad request (as it should) we just choose to print that out. NOT A BUG
