### ISSUE TITLE
Team 3 Phase 3 - Allowed join game with same color

### ISSUE THREAD

**Issue by mwalker9** [cs340tabyu/CatanBugTracker#519]
With own client,
Create and join a game with the color red with a single client open.
Close that client.
Open up 2 clients
log in with two players (one player being the one you already joined with) using two different clients
Hit join (or rejoin) on both clients -- don't pick colors yet.
You should see red is greyed out in one client.  In the client that does not have red greyed out, choose orange (don't hit join game).
In the other client, also choose Orange and hit "Join Game".
Back to the other client, hit "Join Game".
Result:
Game has 2 orange players
Expected result:
error message -- or color disabled after first player changed color to orange.
![image](https://cloud.githubusercontent.com/assets/9952682/11314765/02554456-8fa6-11e5-9b4d-97153172ad65.png)

**Comment by mattshurtz** [comment]
server will not allow this now.
