### ISSUE TITLE
Team 15 Phase 3 - Cannot Join Game

### ISSUE THREAD

**Issue by phelpsdb** [cs340tabyu/CatanBugTracker#522]
Cannot join a game after registering a new user and creating a new game. Tried again as a different registered user, still can't join. I can get as far as the color select modal, but then clicking "Join Game" caused the server and client to both report a NullPointerException. Can't figure out a way to play games.

**Comment by eric-nord** [comment]
Non-issue

**Comment by cs340tabyu** [comment]
To clarify, a file was removed that was necessary for create game.
