### ISSUE TITLE
Team 3 Phase 3 - Built Road For nothing

### ISSUE THREAD

**Issue by mwalker9** [cs340tabyu/CatanBugTracker#524]
Using your client,
Not sure exactly how to replicate this, but
it's my turn.  I have the longest road.  I have enough to build another road.  So, I go to build another road:
![image](https://cloud.githubusercontent.com/assets/9952682/11315000/bd367914-8fa8-11e5-80fd-5bcee8aebb2e.png)
And it builds, and logs as being built, but my resources aren't taken away.
![image](https://cloud.githubusercontent.com/assets/9952682/11315016/fd554d40-8fa8-11e5-86e6-a7b3e827f4b9.png)

**Comment by mattshurtz** [comment]
Garrett said: 
K I fixed 524, and the roadbuilding card, Im going to debug it later before I push it.
im working on other stuff now

**Comment by theroundball** [comment]
Bug fixed.
