### ISSUE TITLE
Team 2 Phase 3 - Too Many Resources

### ISSUE THREAD

**Issue by sebrantley** [cs340tabyu/CatanBugTracker#530]
There is a maximum of 19 resources per resource type.  The players in total have 23 wood resources.
This is probably related to improper resource tracking.

![image](https://cloud.githubusercontent.com/assets/13441798/11315375/dcb47a16-8fad-11e5-8261-c630db363397.png)

**Comment by matt-hoiland** [comment]
See issue #537

**Comment by matt-hoiland** [comment]
Fixed!
