### ISSUE TITLE
Team 2 Phase 3 - Not tracking bank resources (TA Client)

### ISSUE THREAD

**Issue by theroundball** [cs340tabyu/CatanBugTracker#537]
It appears that too many sheep have been handed out to the players. There are 21 sheep total out in players hand's. I think there should be a max at 19(95/5=19). 

![screen shot 2015-11-20 at 6 18 59 pm](https://cloud.githubusercontent.com/assets/7108567/11315676/368638ea-8fb3-11e5-9d41-cf631ad79faa.png)

**Comment by matt-hoiland** [comment]
Potential duplicate with #530

**Comment by matt-hoiland** [comment]
I know _exactly_ where to fix this.

**Comment by matt-hoiland** [comment]
Fixed!
