### ISSUE TITLE
Team 7 Phase 3 - Failed to create game error

### ISSUE THREAD

**Issue by adrfoong** [cs340tabyu/CatanBugTracker#538]
Error message doesn't indicate why game has failed to be created.

![image](https://cloud.githubusercontent.com/assets/9939603/11315671/2c7e4202-8fb3-11e5-86d4-5c872b2e53a1.png)

**Comment by skibum909** [comment]
How did you get this error? When I run the server and the client I never get that, can you explain so I can recreate the bug?
