### ISSUE TITLE
Team 3 Phase 3 - Wrong Amount for Longest Road

### ISSUE THREAD

**Issue by lauracharlotte** [cs340tabyu/CatanBugTracker#539]
It gives me longest road after 4 consecutive roads instead of 5.

**Comment by theroundball** [comment]
If you had '4 consecutive roads' and one road another place on the map that is a total of 5 roads which is how longest road can be implemented. For the other implementation, which is extra credit, you could require 5 consecutive roads. We are implementing the option where whoever has the most roads after having 5 or more is awarded the longest road. 

I believe the situation you are describing above is that you had 4 consecutive and one road somewhere else on the map, totaling 5 roads, so correctly assigning you longest road. 

![screen shot 2015-11-21 at 11 25 23 am](https://cloud.githubusercontent.com/assets/7108567/11319879/c722042a-9043-11e5-9ff5-d2bbd2904870.png)

Here you can see that with only 4 roads you do not get the longest road. 

![screen shot 2015-11-21 at 11 30 19 am](https://cloud.githubusercontent.com/assets/7108567/11319881/d7856456-9043-11e5-802e-4460584f9cd7.png)

build one more you do, regardless of it being consecutive in this case vs. the first image case.

![screen shot 2015-11-21 at 11 30 32 am](https://cloud.githubusercontent.com/assets/7108567/11319883/f013f640-9043-11e5-82d6-d786be687bd8.png)

**Comment by mattshurtz** [comment]
NOT A BUG
