### ISSUE TITLE
Team 18 Phase 2 - Able to try to buy dev card during someone else's turn

### ISSUE THREAD

**Issue by colingm** [cs340tabyu/CatanBugTracker#54]
Steps:
- Have enough resources to buy a development card
- During another player's turn click the button to buy a dev card and the modal appears

Result:
- It acts as if you can buy a card during their turn (since buying a dev card doesn't work nothing happens)

Expected Result:
- The dev card button should be disabled when it isn't your turn

![image](https://cloud.githubusercontent.com/assets/11670266/10777899/de10bae4-7ce5-11e5-9707-ed6f55a520c7.png)

**Comment by jordantgates** [comment]
All building options now disabled per spec sheet, please close
