### ISSUE TITLE
Team 2 Phase 3 - Robber Not Working (TA Client)

### ISSUE THREAD

**Issue by theroundball** [cs340tabyu/CatanBugTracker#540]
-I rolled a 7
-I was prompted to place robber with robber modal
-I placed the robber on modal
-modal closed
-Robber was not moved and this is my screen. Game is stalled 

![screen shot 2015-11-20 at 6 20 52 pm](https://cloud.githubusercontent.com/assets/7108567/11315691/9550267e-8fb3-11e5-92c4-a3a66d227ff6.png)

**Comment by theroundball** [comment]
UPDATE:

While testing on the TA client I was prompted to rob and everything seemed to function correctly when I rolled a 7. The only difference between the two scenarios I can see was that, in this case, the player who rolled a 7 had more than 7 cards and was also prompted to discard. 

I don't know why this would be happening. I hope that scenario makes sense.

**Comment by matt-hoiland** [comment]
It was due to a null pointer exception interrupting the command call when robbing no one.  It is now fixed.
