### ISSUE TITLE
Team 3 Phase 3 - Says robbed when robbed nobody.

### ISSUE THREAD

**Issue by lauracharlotte** [cs340tabyu/CatanBugTracker#541]
When player moves robber, but moves it to a place that no one is at and robs no one, the Game History say “_player_ robbed” instead of nothing. (Your client)

**Comment by mattshurtz** [comment]
No specifications on what game history should say given a move. Thus it is still appropriate for us to say a player robbed. Although no card was taken from anyone, the robber 'robs' players from potential future resources. ;) SHOULD NOT BE A BUG.
