### ISSUE TITLE
Team 2 Phase 3 - Swagger not implemented message (May not be Bug)

### ISSUE THREAD

**Issue by theroundball** [cs340tabyu/CatanBugTracker#545]
I'm not sure if this is a bug or I just don't understand how to access your server through swagger. 

I started your server, when to localhost:8081 and I see this 
![screen shot 2015-11-20 at 6 37 29 pm](https://cloud.githubusercontent.com/assets/7108567/11315810/ef92921e-8fb5-11e5-8b39-e0826c3087c1.png)

**Comment by matt-hoiland** [comment]
While we aren't supposed to test each others' swagger, I wanted to make sure it was available to you as a diagnostics tool.  You have to specifically hit localhost:8081/docs/api/view/index.html
