### ISSUE TITLE
Team 2 Phase 3 - Buy Dev Card Enabled but not working (TA Client)

### ISSUE THREAD

**Issue by theroundball** [cs340tabyu/CatanBugTracker#546]
Buy a dev card is properly enabled, but clicking buy card seems to only close the modal, resources are not decremented and development card is not given to the player 
![screen shot 2015-11-20 at 6 45 43 pm](https://cloud.githubusercontent.com/assets/7108567/11315869/f1d30c1a-8fb6-11e5-85d6-42c53c7c5956.png)

![screen shot 2015-11-20 at 6 45 51 pm](https://cloud.githubusercontent.com/assets/7108567/11315871/f5c6c6ea-8fb6-11e5-8156-a8e19ec73d7e.png)

**Comment by matt-hoiland** [comment]
Fixed
