### ISSUE TITLE
Team 3 Phase 3 - Finishing game logs you out 

### ISSUE THREAD

**Issue by madisonjbrooks12** [cs340tabyu/CatanBugTracker#549]
When I finish a game and click "OK" on my losing/winning popup, it logs me out and restarts the client instead of taking me back to the game hub.

**Comment by mattshurtz** [comment]
TA's said this is not a bug. It is ok to implement this way. NOT A BUG.

**Comment by madisonjbrooks12** [comment]
No need to get angry. Your code was great, it took me hours to find any bugs. If it's not a bug, the TAs won't count you off for it.

**Comment by mattshurtz** [comment]
Sorry. I am all caps the NOT A BUG so i can find it easier when reviewing with TAs. My comments are not directed towards group.
