### ISSUE TITLE
Team 3 Phase 2 - Client throws StackOverflowError when canceling road, settlement, or city placement

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#55]
To reproduce:

Start a game and play until you have enough resources to build a road/settlement/city.
Click the road/settlement/city icon to begin building a road/settlement/city.
When the place road/settlement/city modal appears, press cancel.
**StackOverflowError thrown**

**Comment by theroundball** [comment]
## We added a fix, so that the build modals did not try to repaint if they were not showing.

## Bug Fixed

**Comment by mattshurtz** [comment]
never really was a bug because the user would never see the stackoverflow unless looking at the console.
