### ISSUE TITLE
Team 18 Phase 2 - When prompted to discard it shows cards selected from previous discard

### ISSUE THREAD

**Issue by colingm** [cs340tabyu/CatanBugTracker#56]
Steps:
- Have the option to discard and choose cards to discard
- Let play continue and gain enough cards to discard again
- Have someone roll a 7

Results:
- The modal will appear with the cards that you discarded last time shown but it acts as if they are at 0 (the bottom says 0, the down arrows are disabled, and if you increase the amount it goes to 1)

Expected Results:
- Every time you have to discard it appears as a fresh screen with all 0's for the resources to discard

![image](https://cloud.githubusercontent.com/assets/11670266/10777953/72c7d73a-7ce6-11e5-91ac-4a62252be705.png)

**Comment by jordantgates** [comment]
Good catch! Code updated to reset to 0 when discarding. Please close
