### ISSUE TITLE
Team 1 Phase 3 -- Cannot dismiss Domestic Trade Overlay

### ISSUE THREAD

**Issue by matt-hoiland** [cs340tabyu/CatanBugTracker#561]
Steps to reproduce:

Launch server.
Launch your client.
Join first game.
Roll to start turn.
Click on a few buttons (I clicked on the play dev card, buy dev card, and the build city, settlement, and road buttons)
Click domestic trade
Click cancel, modal flashed but immediately returned.
Subsequent clicks on cancel do nothing

![image](https://cloud.githubusercontent.com/assets/14057598/11316441/716f2e74-8fc4-11e5-87ca-a9409af16eea.png)

**Comment by liukaichi** [comment]
Bug fixed
