### ISSUE TITLE
Team 1 Phase 3 - Wrong user signed in when registering new user

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#562]
When registering a new user (in the example below, a user named 'second'), the server appears to be logging them in as a preexisting user (able to re-join full games).

![screenshot 2015-11-20 19 12 58](https://cloud.githubusercontent.com/assets/14239472/11316097/c5d3ea94-8fbb-11e5-9629-ba1d78a6e9e0.png)

**Comment by matt-hoiland** [comment]
Can confirm, just logged in as Cache, joined Empty Game and the client thinks I'm Brooke: 
![cache is brooke](https://cloud.githubusercontent.com/assets/14057598/11316630/01758a34-8fcc-11e5-9e0f-a98cfdb49f9f.jpg)

**Comment by liukaichi** [comment]
bug fixed.
