### ISSUE TITLE
Team 1 Phase 3 -- Team 1 server incompatible with Team 2 client

### ISSUE THREAD

**Issue by matt-hoiland** [cs340tabyu/CatanBugTracker#565]
Since Dr. Snell wanted servers to serve all clients equally, I tried to run our client with Team 1's server.  Issue #508 already documents its incompatibility with the TA client, the same behavior persists with our client.  To verify, I started the server fresh and relaunched our client.

**Comment by liukaichi** [comment]
Could you send us your client so we can test? Thank you.

**Comment by theshecoder** [comment]
Since we do not have your client, we cannot replicate this. However, we can now run our server with the TA client code.

**Comment by matt-hoiland** [comment]
If you'd still like to verify that it works with our client, here is a link to our phase 3 tester zip. https://drive.google.com/file/d/0B27ZnDS6HQHkQ2ZsYkhLQTAzOUE/view?usp=sharing
