### ISSUE TITLE
Team 1 Phase 3 -- Not communicating properly the players as they join a game

### ISSUE THREAD

**Issue by matt-hoiland** [cs340tabyu/CatanBugTracker#567]
Steps to reproduce:
Launch server (Team 1)
Launch client (either TA or Team 2)
Login as Sam
Create new game (no randomness)
Join new game

Steps performed with Team 2 Client and Team 1 server:
![initial player not shown](https://cloud.githubusercontent.com/assets/14057598/11316549/e580933a-8fc8-11e5-89b7-92384b0389a0.jpg)

When reproduced with Team 2 Client and Server (all our code):
![player waiting on my server](https://cloud.githubusercontent.com/assets/14057598/11316553/05da3d02-8fc9-11e5-8b8a-e1f5c60db141.jpg)

When reproduced with TA Client and Team 2 Server (our server):

![image](https://cloud.githubusercontent.com/assets/14057598/11316535/6b1656c0-8fc8-11e5-98ed-287b9a0c8321.png)

**Comment by liukaichi** [comment]
Bug fixed.
