### ISSUE TITLE
Team 1 Phase 3 -- Unable to rejoin game to which user seemingly belongs

### ISSUE THREAD

**Issue by matt-hoiland** [cs340tabyu/CatanBugTracker#568]
Steps to reproduce:
Launch fresh Team 1 server
Sign in as Amanda
Unable to join game CS340 as Amanda

![image](https://cloud.githubusercontent.com/assets/14057598/11316600/cfc5ec46-8fca-11e5-9436-0243765a5376.png)

**Comment by liukaichi** [comment]
Bug fixed.
