### ISSUE TITLE
Team 1 Phase 3 -- Road Build in First Round worked, but wasn't prompted to place settlement

### ISSUE THREAD

**Issue by matt-hoiland** [cs340tabyu/CatanBugTracker#572]
Steps to reproduce:
Launch new server
Login as Sam
Join empty game
Place first road
Observe that the place settlement modal was not shown
![image](https://cloud.githubusercontent.com/assets/14057598/11316641/6df68096-8fcc-11e5-878a-bcd8a027aa43.png)

**Comment by liukaichi** [comment]
Bug fixed.
