### ISSUE TITLE
Team 1 Phase 3 -- All right panel buttons enabled but the build buttons aren't clickable (minor)

### ISSUE THREAD

**Issue by matt-hoiland** [cs340tabyu/CatanBugTracker#573]
When logged in as sam in the first game, after rolling, all buttons on the right panel seem active, but the only two that show modals are buy and play dev cards, the build buttons do nothing (road and settlement are okay, but sam should be able to build a city)

![image](https://cloud.githubusercontent.com/assets/14057598/11316670/cfa696f4-8fcd-11e5-94e6-23c8e8fee96f.png)

**Comment by liukaichi** [comment]
Bug fixed
