### ISSUE TITLE
Team 6 Phase 3: Setup Phase in wrong order

### ISSUE THREAD

**Issue by zachanator070** [cs340tabyu/CatanBugTracker#574]
The setup phase is supposed to have you place a road THEN a settlement. Currently is the opposite.

**Comment by xuther** [comment]
See catan rules, page 11-12:

The starting player places a settlement on an open intersection of his choice. He places a road adjacent to this settlement. 

http://www.catan.com/en/download/?SoC_rv_Rules_091907.pdf

**Comment by yoojeong** [comment]
Not a bug. :)
