### ISSUE TITLE
Team 6 Phase 3 Waiting for players to discard

### ISSUE THREAD

**Issue by skibum909** [cs340tabyu/CatanBugTracker#575]
When more than one player had to discard, the window came up to discard but after I discarded the "Waiting for Other Players to Discard" window never popped up for me even though I was still waiting for others to discard. After the other players finished discarding, the game just hung there. Sending a chat made the "Waiting for Other Players to Discard" to pop up for another player who couldn't see it, but since the player whose turn it was had "Waiting for Other Players to Discard" modal, he couldn't send a chat and therefore the game was frozen indefinitely and had to be closed.

**Comment by xuther** [comment]
We were able to recreate the issue if the player who discarded had 7 cards, even after having discarded (i.e He had more than 14 cards pre-discarding). It's been fixed.
