### ISSUE TITLE
Team 6 Phase 3 Placing second road

### ISSUE THREAD

**Issue by skibum909** [cs340tabyu/CatanBugTracker#576]
I can build place my second road during the setup phase on my first settlement. This means that I leave my second settlement without roads and therefore I can never build a road coming off my second settlement for the rest of the game.

**Comment by xuther** [comment]
Good point. Whoops!

**Comment by xuther** [comment]
Fixed. I think that's why the provided client does road -> Settlement. it gets around that issue.
