### ISSUE TITLE
Team 6 Phase 3 

### ISSUE THREAD

**Issue by skibum909** [cs340tabyu/CatanBugTracker#583]
I had a "Year of Plenty Dev Card" and a "Monopoly Dev Card" that I had bought many turns ago. When I open the window, they were both available to play. Then I bought a dev card that ended up being a "Soldier" and then when i opened the window, not only could I not play the "Soldier Dev Card" (which is correct), I couldn't play the "Year of Plenty Dev Card" of the "Monopoly Dev Card" anymore even though they were purchased many turns ago.

**Comment by xuther** [comment]
Fixed
