### ISSUE TITLE
Team 6 Phase 3 create games

### ISSUE THREAD

**Issue by skibum909** [cs340tabyu/CatanBugTracker#585]
You can't create a game with spaces in it.

**Comment by yoojeong** [comment]
Are you saying that we should not create a game with spaces in it? Because I WAS able to create a game with spaces on ours just now.

**Comment by skibum909** [comment]
When I ran your server I got an error back saying there was something that
didn't work in parsing with spaces. So I don't know how you created a game
with spaces in it, but it DID NOT WORK when I tried to do so.

**Comment by yoojeong** [comment]
okay I'll look into it again then.
