### ISSUE TITLE
Team 6 Phase 3 Name creation 

### ISSUE THREAD

**Issue by skibum909** [cs340tabyu/CatanBugTracker#586]
can create a user with hyphens and underscores which are not allowed

**Comment by xuther** [comment]
Cannot find relative piece in specs. 

The paragraph pertaining to username and password restrictions reads:

Registering a new user should reject the registration if the username is fewer than 3 or greater than
seven characters, if the password is less than 5 characters long or is not made of allowed characters
(alphanumerics, underscores, hyphens, or if the password verification entry doesn’t match the original.)

Clearly stating that there are only length requirements on the username, and that the password MAY contain hyphens and underscores.
