### ISSUE TITLE
Team 3 Phase 2 - Resource bar displays odd warning

### ISSUE THREAD

**Issue by clayellis** [cs340tabyu/CatanBugTracker#59]
I believe this is an artifact of not displaying the roll modal immediately after a player's turn begins, but merits another bug report on its own. The resource bar displays an odd warning when attempting to build something before a player has rolled.

Steps to reproduce:
- Start a new turn
- _Quickly_ click to build something 
- You'll get this error: 
  <img width="1376" alt="screen shot 2015-10-27 at 7 54 58 pm" src="https://cloud.githubusercontent.com/assets/10712068/10777949/68c62e12-7ce6-11e5-8e4f-6cb79ac67608.png">
- I have no idea what that error is, but you shouldn't be able to build anything before a roll as per the game rules: **On your turn, you can do the following in the order listed: 1. You must roll for resource
  production... - Game Rules: pg. 4**

**Comment by ramorris3** [comment]
We had a line of code that was closing modals when it shouldn't have been.  This has been fixed now.  Thanks.

## Bug Fixed
