### ISSUE TITLE
Team 6 Phase 3 First turn

### ISSUE THREAD

**Issue by skibum909** [cs340tabyu/CatanBugTracker#590]
![12247982_10153766508691310_2009214866892783201_o](https://cloud.githubusercontent.com/assets/8333655/11316716/ac9991f0-8fcf-11e5-883e-d3e0ea8fb23e.jpg)
I rolled an 11 and got two wood. It was my first roll of the game and I was the first player to go. See screen shot

**Comment by xuther** [comment]
The resources were the resources rewarded to you from your second settlement placement - as per the rules. 

You were rewarded one brick for the roll.

**Comment by skibum909** [comment]
Oops, That makes sense now.

**Comment by yoojeong** [comment]
Not a bug. :)
