### ISSUE TITLE
Team 6 Phase 3 no pictures displayed

### ISSUE THREAD

**Issue by jessethomson** [cs340tabyu/CatanBugTracker#593]
![12249587_10153766508426310_2897987996861869793_n](https://cloud.githubusercontent.com/assets/15367855/11316721/0a836b1a-8fd0-11e5-833d-9e339eb15f72.jpg)
When sending a trade the receiver does not have a picture displayed of what resource it is. See screen shot

**Comment by xuther** [comment]
Umm... could not replicate. 

Not an issue with student-generated code, issue would be with GUI (provided) code.
