### ISSUE TITLE
Team 6 Phase 3 color selection

### ISSUE THREAD

**Issue by jessethomson** [cs340tabyu/CatanBugTracker#597]
The game will let multiple people pick the same color.

**Comment by xuther** [comment]
Need to check.

**Comment by xuther** [comment]
Could not replicate. Possible that would arise from selecting a color before the client could sync with the server.

**Comment by yoojeong** [comment]
Fixed

**Comment by yoojeong** [comment]
Other than the synchronization issue, it's been fixed.
