### ISSUE TITLE
Team 6 Phase 3 Ports 

### ISSUE THREAD

**Issue by jessethomson** [cs340tabyu/CatanBugTracker#600]
![12227059_10205363393025162_5620445797425695282_n](https://cloud.githubusercontent.com/assets/15367855/11316745/be0aad24-8fd0-11e5-9ac5-7546924234f4.jpg)
the ports aren't set up correctly. There should be one for each type of resource and then the rest are universal ports, see screen shot.

**Comment by xuther** [comment]
Fixed.
