### ISSUE TITLE
Team 2 Phase 3 - Can't create game (TA Client)

### ISSUE THREAD

**Issue by mattshurtz** [cs340tabyu/CatanBugTracker#602]
When trying to create game, nothing happens when I click create game. I logged in as Sam. The TA's client throws a null pointer. It does not matter what combination of random parts selected. Nor what the title is.

![image](https://cloud.githubusercontent.com/assets/7896173/11316755/34d2d79c-8fd1-11e5-9268-23086d2de0a2.png)

**Comment by mattshurtz** [comment]
apparently it did add game, but did not go back to game hub page.

**Comment by matt-hoiland** [comment]
I claim this

**Comment by matt-hoiland** [comment]
Fixed
