### ISSUE TITLE
Team 1 Phase 3 - Able to start development card buy without necessary resources

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#605]
Began turn with enough resources to buy development card. Used maritime trade to lose stone until Sam did not have enough resources to buy the dev card. Dev card buy modal still appears, although clicking buy seems to do nothing.
![screenshot 2015-11-20 22 15 20](https://cloud.githubusercontent.com/assets/14239472/11316820/9ae0d216-8fd4-11e5-864d-d49188313ba4.png)

**Comment by adrfoong** [comment]
Fixed.
