### ISSUE TITLE
Team 1 Phase 3 - Inconsistent player list

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#606]
Brooke is listed as a member of the default game:
![screenshot 2015-11-20 22 00 15](https://cloud.githubusercontent.com/assets/14239472/11316834/dddf96e2-8fd4-11e5-80ec-e700ecfd0d89.png)
but upon entering the game, Amanda is listed instead:
![screenshot 2015-11-20 22 00 04](https://cloud.githubusercontent.com/assets/14239472/11316838/f413f412-8fd4-11e5-96a2-af344a3b288e.png)
Same thing happens with sheila instead of Mark

**Comment by liukaichi** [comment]
Updated files to match. Bug fixed
