### ISSUE TITLE
Team 15 Phase 3 - Server NoSuchFileException for Json Files

### ISSUE THREAD

**Issue by phelpsdb** [cs340tabyu/CatanBugTracker#627]
The server is shooting errors when the game list is first loaded. It cannot find a file named "firstgame.json". When I create a game, the game appears to be successfully created, but for some reason the server throws an error saying it can't find "basicGame.json".

The server does not crash from these errors, but I don't know if they are related to the fact that I am unable to join any games (reported in previous ticket).

**Comment by eric-nord** [comment]
Non-issue
