### ISSUE TITLE
Team 3 Phase 2 - Incorrect Win Screen

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#63]
To reproduce:
?

Created a game, joined it (client hung)
Added 3 AIs to game through Swagger
Restarted client, played through game
Won game by placing a city
Lost game screen shown, player shown as winning is next in line

![screenshot 2015-10-27 20 25 37](https://cloud.githubusercontent.com/assets/14239472/10778197/1458ec04-7ce9-11e5-9bf2-8fe944ab1f39.png)

**Comment by ramorris3** [comment]
We fixed this by adding a check to the "setScore" function.  You shouldn't see this problem any more.  Thanks.

## Bug Fixed
