### ISSUE TITLE
Team 3 Phase 2 - "You Win" modal didn't show up on a win

### ISSUE THREAD

**Issue by clayellis** [cs340tabyu/CatanBugTracker#64]
I won the game and the "You Win" modal didn't show. I won with the final move being placing a settlement. I had the longest road and largest army (_See image_) Even after playing another round it didn't show up

<img width="1350" alt="screen shot 2015-10-27 at 8 35 20 pm" src="https://cloud.githubusercontent.com/assets/10712068/10778331/95869528-7cea-11e5-98e1-04c9a6d35b7d.png">

**Comment by ramorris3** [comment]
We had an issue where the "setScore" function was breaking whenever you win by more than exactly 10 points.  This was the problem behind the win modal not popping up.  We added a check to the "setScore" function, so now it doesn't try to push a value greater than 10 to the view or the server, so it's fixed now.

## BUG FIXED
