### ISSUE TITLE
Team 3 Phase 2 - Turn Tracker does not update to show color changes

### ISSUE THREAD

**Issue by miarodri** [cs340tabyu/CatanBugTracker#65]
To reproduce:
Start 2 clients
Log in as Sam on one client and Brooke on the second.
Join Empty Game (id 2) as Sam. Note Brooke's color on the turn tracker.
Join Empty Game (id 2) as Brooke. Choose a color different that what Sam's client shows and join game.
**Sam's client does not update Brooke's color**

![screenshot 2015-10-27 20 35 03](https://cloud.githubusercontent.com/assets/14239472/10778315/6715146c-7cea-11e5-9be1-11b357f6ede6.png)

**Comment by theroundball** [comment]
This is fixed, but the color change does not occur until the next action is performed and the views are refreshed. 

---

## bug Fixed
