### ISSUE TITLE
Group 2 Phase 2 -- Robbing errors

### ISSUE THREAD

**Issue by liukaichi** [cs340tabyu/CatanBugTracker#67]
The first robbing state worked, but after that, only the discard worked (there was no placeRobber stuff called). Also, the robber location is not being updated on the server. The other players' robber is still in the old location. 

Here's a picture. Sorry if it's small. The left bottom client moved the robber, but the other robbers are still in the original spot

![robber and robbing bug](https://cloud.githubusercontent.com/assets/7852745/10778665/08401fc8-7cee-11e5-9832-5ed03ca94acc.PNG)

**Comment by matt-hoiland** [comment]
Matt

**Comment by cs340tabyu** [comment]
To clarify, after all players discard, the robber does not get moved.
