### ISSUE TITLE
Group 2 Phase 2 - end turn during discard

### ISSUE THREAD

**Issue by longlostbro** [cs340tabyu/CatanBugTracker#74]
During discard state, it allows the player with current turn to end turn.
It then changes turn to next player and allows player to roll, and doesn't require him to discard.
![image](https://cloud.githubusercontent.com/assets/5777927/10779062/8abebc5e-7cf1-11e5-9fee-b3e0e8ad58cc.png)

**Comment by liukaichi** [comment]
I kept going with a similar problem, with Pete having rolled again, and then later when I run into a robber, it ends up being this. I currently can't do anything.

![image](https://cloud.githubusercontent.com/assets/7852745/10779200/0747b7c0-7cf3-11e5-87fc-930850298e88.png)

**Comment by longlostbro** [comment]
Then if the player with current turn closes client and reopens it pops up his discard modal, then you can continue the game

**Comment by clayellis** [comment]
@longlostbro @liukaichi Please list exact steps to reproduce.
