### ISSUE TITLE
Group 2 phase 2 - Player Colors are not set properly when a player joins with a different game

### ISSUE THREAD

**Issue by cache117** [cs340tabyu/CatanBugTracker#75]
Colors are not fully synchronized between clients.
![image](https://cloud.githubusercontent.com/assets/11652513/10779129/350444a4-7cf2-11e5-996e-f9e89d48e42a.png)
![image](https://cloud.githubusercontent.com/assets/11652513/10779131/37d8e25c-7cf2-11e5-87a5-356a00e9c312.png)

**Comment by matt-hoiland** [comment]
Issue has been noted.

**Comment by miarodri** [comment]
Color now updates, though update may be slightly delayed.
