### ISSUE TITLE
Team 5 Phase 2 -- Low priority

### ISSUE THREAD

**Issue by mwalker9** [cs340tabyu/CatanBugTracker#8]
Steps:
1) Login
2) Join game controller comes up
3) Click create new game
4) Enter nothing into title or "2341807%$#@"
Result:
Nothing happens
Expected result:
Some type of error message/sign something happened

**Comment by tkwilli94** [comment]
Fixed. We only allow alphanumeric game names (spaces are allowed) with a length greater than 1. The error dialog now shows up upon invalid game names.
