### ISSUE TITLE
Team 18 Phase 2 - placing roads and settlements (DUPLICATE)

### ISSUE THREAD

**Issue by jaredcrystal** [cs340tabyu/CatanBugTracker#80]
Steps:
-Tried to place roads and settlements on the water hexes

Result:
-Allowed

Expected Result:
-Not allow placing of anything on water hexes

![image](https://cloud.githubusercontent.com/assets/14153009/10791076/6598ed72-7d4c-11e5-8e48-66c381e51fed.png)

**Comment by colingm** [comment]
I think this is only possible during the initial setup rounds

**Comment by ojaneeo** [comment]
You are also able to place your road on top of roads of other players
