### ISSUE TITLE
Group 2 Phase 2 "Finish Turn" button does not change color according to player

### ISSUE THREAD

**Issue by theshecoder** [cs340tabyu/CatanBugTracker#99]
The "Finish Turn" button at the bottom of the page should update to the color of the local player.

**Comment by clayellis** [comment]
@theshecoder Please reference this requirement in the Technical Specification document. The demo client doesn't have this functionality.

**Comment by theshecoder** [comment]
Number 9 of the phase 2 implementation notes.
